### ISSUE TITLE
build: remove `System.import()` warnings for @angular/core

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1004]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

We get the following warning during the build: 
![image](https://user-images.githubusercontent.com/10333565/50695627-7e541580-103d-11e9-8d68-22a4c2b63cc1.png)

See https://github.com/angular/angular/issues/21560, angular has an issue with `System.import()` calls in \@angular/core. They apparently do not plan to solve it.

In \@angular/cli, they added the following code in their webpack configuration to ignore the warnings about this issue.

```js
{
      // Mark files inside `@angular/core` as using SystemJS style dynamic imports.
      // Removing this will cause deprecation warnings to appear.
      test: /[\/\\]@angular[\/\\]core[\/\\].+\.js$/,
      parser: { system: true },
}
```

## Expected behavior

We have no control on the angular code so we should the apply the same rule in our build.

## Minimal reproduction of the problem with instructions

Run `npm start` and you will get the same warnings.

## What is the motivation / use case for changing the behavior?

Remove useless warnings

## Environment

<pre><code>
Angular version: 7.1.x
Stark version: 10.0.0-beta.1

</code></pre>

**Comment by christophercr** [comment]
Closed in #1006
