### ISSUE TITLE
ui: icons are not in the middle of buttons

### ISSUE THREAD

**Issue by cnomes** [NationalBankBelgium/stark#1030]
## I'm submitting a...

<pre><code>
[?] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Depending on the browser the icon is offset from the center.

## Expected behavior

The icon is in the middle.

## Environment

<pre><code>
Angular CLI: 7.2.1
Node: 11.4.0
OS: darwin x64
Angular: 7.1.1

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

Others:

    "@angular/material": "7.2.0"
</code></pre>

**Comment by cnomes** [comment]
Maybe relate to https://github.com/NationalBankBelgium/stark/issues/504

**Comment by cnomes** [comment]
Example: https://angular-esdwwf.stackblitz.io/
Related: https://github.com/angular/material2/issues/8842

**Comment by christophercr** [comment]
Apparently there is an issue on Angular Material repo tracking this issue: https://github.com/angular/material2/issues/8842
