### ISSUE TITLE
ui: add layouts and layout classes

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#106]
Integrate our layout classes and utility classes

**Comment by christophercr** [comment]
Discussing with Julien, he mentioned that this could be completely replaced by https://github.com/angular/flex-layout in the client apps.

In fact there is already an issue created for this: #668.

We need to discuss whether this is the approach we want to follow or to keep using the stark layout classes as before.

**Comment by christophercr** [comment]
After discussing this with Carlo, we've decided not to implement the layout classes from the old Stark but suggest to use the new https://github.com/angular/flex-layout library.
