### ISSUE TITLE
ui: Generic Search - Search form is not reset when click on reset button

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1125]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When the user clicks on the **reset** button in the generic search component, the search form is not resetted.

## Expected behavior

When click on reset, the search form should be resetted.

## Environment

<pre><code>
Angular version: 7.x.x
Stark version: 10.0.0-beta.3

**Comment by SuperITMan** [comment]
done in 10.0.0-beta.4

**Comment by christophercr** [comment]
Re-opening as this issue has not been fixed. See https://stark.nbb.be/showcase/10.0.0-beta.4/demo-ui/generic-search
