### ISSUE TITLE
build: rollup - optimize rollup.config usage with functions

### ISSUE THREAD

**Issue by carlo-nomes** [NationalBankBelgium/stark#1129]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[X] Optimisation
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

All external libraries need to be added one by one, each subpackage seperatly.

## Expected behavior

Replace this with functions to automatically decide how they should be mapped.

**Comment by christophercr** [comment]
Closing this issue as it is obsolete now that we use `ng-packagr` to build the stark packages implemented in #1360
