### ISSUE TITLE
build: bundles design

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#114]
Currently we've started from the most recent Angular Starter version. In the webpack common config, two entry points are defined: main & polyfills
-> https://github.com/gdi2290/angular-starter/blob/master/config/webpack.common.js

In our Stark "v1", we had more than that:
* polyfills: src/polyfills.ts
* vendor-styles: src/vendor-styles.ts
* main-styles: src/main-styles.ts
* vendor: src/vendor.ts
* main: src/main.ts

This was useful for caching. Now indeed things may be changing with AOT, lazy loading, ...

So we need to decide what to do with our bundles

**Comment by dsebastien** [comment]
* [ ] Document lazy loading of modules
* [ ] Do we need main-style entry point?
* [ ] Do we need vendor and vendor-style entry point?

**Comment by christophercr** [comment]
After discussing the topic, we agreed on the following:

* [ ] Document lazy loading of modules
* [ ] Create **main** entry point for the app code
* [ ] Create **vendor** entry point for Stark + vendor code
* [ ] Create **styles** entry point for global styles including the cherry picked stark component styles
* [ ] Create **polyfills** entry point for polyfills from the app (which should import the polyfills from Stark)
* [ ] Create **runtime** entry point for Webpack runtime reusable code (`runtimeChunk` option in Webpack optimization config)

With this setup, we will be able to leverage the DLL feature of Webpack for the vendor bundle.

**Comment by christophercr** [comment]
This will be tackled together with #883

**Comment by christophercr** [comment]
Solved in #1148
