### ISSUE TITLE
build: typescript - loosen TS configuration to allow type Inference

### ISSUE THREAD

**Issue by cnomes** [NationalBankBelgium/stark#1144]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Currently when coding typing has to be done very explicitly, this could be reduced by allowing (forcing) type inference through linting.
links:
TypeScript [Type Inference](https://www.typescriptlang.org/docs/handbook/type-inference.html)
TSLint: [no-inferrable-types](https://palantir.github.io/tslint/rules/no-inferrable-types/)

## What is the motivation / use case for changing the behavior?

IMHO this would lead to cleaner code.

**Comment by christophercr** [comment]
As discussed we can take the chance to also enable the flag [strictPropertyInitialization](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#strict-class-initialization) in our TS config. We disabled it a while ago because it was not supported by our version of IntelliJ back then.

**Comment by cnomes** [comment]
@christophercr @SuperITMan with the `strictPropertyInitialization` I have to do a lot of refactoring. But I have code-style question before I start. Do we prefer initializing class properties at declaration or in the constructor.
I prefer at declaration, because then there is a lot less jumping around in the code to find the (initial) value of a property. But I wanted to discuss this before I start working on it. 😄

**Comment by christophercr** [comment]
As discussed, we should initialize the properties at the declaration otherwise we will force the developer to implement a constructor just to set the values of the properties even if the class doesn't really need a constructor
