### ISSUE TITLE
core: error - Angular exception handling

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#116]
In Stark "v1" we had the following:
* errorOnUnhandledRejections (for promises)
* custom $exceptionHandler
* ...

We should have at least the same support with the new version

**Comment by christophercr** [comment]
See: https://angular.io/api/core/ErrorHandler

**Comment by dsebastien** [comment]
Ok nice.
We should tap into that API as well as ui-router's, etc and provide default global handlers, for example adding to the console, generating redux actions, updating the message pane or showing a global error page if it's something we can't deal with.

The alternative is just letting developers handle it on their own.

**Comment by christophercr** [comment]
After discussing with @Mallikki, the apprach will be to replace the Angualr default error handler with our own in which we will dispatch an Redux action which can be handled by the developers as they wish via NGRX effects.

Such handler will be also used by the Router ;)
