### ISSUE TITLE
ui: route-search - transparency issue on Chrome 56

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1181]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

On Chrome 56, when opening the search-route, there is an unwanted transparency.
![image](https://user-images.githubusercontent.com/10333565/54033228-08db0180-41b4-11e9-9876-d973890f5baf.png)

In stark 10.0.0-beta.4 it was working correctly.

## Expected behavior

The background of the route-search should be blank instead of transparent.

## Minimal reproduction of the problem with instructions

Open showcase on Chrome v56 or IE 11

## Environment

<pre><code>
Angular version: X.Y.Z
Stark version: 10.0.0-beta.5

Browser:
- [X] Chrome (desktop) version 56
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version 11
- [X] Edge version 41.16299.820.0
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cnomes** [comment]
Also the border on the references
