### ISSUE TITLE
core: session

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#119]
Integrate Stark session.
Try and isolate in a dedicated module / package.

The behavior should only be enabled for NBB apps

* [x] session configuration
* [x] session initialization (user, user service, user repository, profile loading, ...)
* [x] session timeout handling
* [x] session expired page
* [x] session timeout warning dialog
* [X] logout and logout page

**Comment by christophercr** [comment]
Closed in #876
