### ISSUE TITLE
starkSvgViewBox directive doesn't update viewBox of custom SVG already containing viewbox

### ISSUE THREAD

**Issue by dede-pon** [NationalBankBelgium/stark#1216]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
When using the starkSvgViewBox directive on a custom svg, if that svg already has a viewBox set, the directive doesn't change it.

## Expected behavior
The viewBox should be changed to the configured one.

## Minimal reproduction of the problem with instructions
In any component, use a mat-icon with a custom svg file (which should be imported).
In the mat-icon component, add the starkSvgViewBox directive and change the default value.

## What is the motivation / use case for changing the behavior?
Resize the icons to fit the design.

## Environment

<pre><code>
Angular version: 7.x
Stark version: 10.0.0-beta.6

Browser:
- [X] Chrome (desktop) version 56
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by dede-pon** [comment]
Custom icon code : 

<code>

<?xml version="1.0" encoding="UTF-8"?>
<svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <path d="M27.5463535,19.3138534 C27.9648247,18.8953822 28.6433005,18.8953822 29.0617717,19.3138534 C29.4802429,19.7323246 29.4802429,20.4108005 29.0617717,20.8292717 L24.7755216,25.1155218 C24.3570504,25.533993 23.6785746,25.533993 23.2601034,25.1155218 L18.9738532,20.8292717 C18.555382,20.4108005 18.555382,19.7323246 18.9738532,19.3138534 C19.3923244,18.8953822 20.0708003,18.8953822 20.4892715,19.3138534 L24.0178125,22.8423944 L27.5463535,19.3138534 Z" fill="#1073DE" fill-rule="nonzero" transform="translate(24.017812, 22.214688) rotate(-180.000000) translate(-24.017812, -22.214688) "></path>
        <path d="M22.9300003,21.0715625 C22.9300003,20.4797549 23.4097552,20 24.0015628,20 C24.5933705,20 25.0731254,20.4797549 25.0731254,21.0715625 L25.0731254,42.5028131 C25.0731254,43.0946207 24.5933705,43.5743756 24.0015628,43.5743756 C23.4097552,43.5743756 22.9300003,43.0946207 22.9300003,42.5028131 L22.9300003,21.0715625 Z" fill="#1073DE" fill-rule="nonzero"></path>
        <path d="M18.4300003,35.7896883 C19.0218079,35.7896883 19.5015628,36.2694432 19.5015628,36.8612509 C19.5015628,37.4530585 19.0218079,37.9328134 18.4300003,37.9328134 L11.2862501,37.9328134 C9.1266821,37.9328134 7.35718751,36.2402534 7.35718751,34.1279899 L7.35718751,8.16201098 C7.35718751,6.04974755 9.1266821,4.35718751 11.2862501,4.35718751 L37.0037508,4.35718751 C39.1633188,4.35718751 40.9328134,6.04974755 40.9328134,8.16201098 L40.9328134,34.1279899 C40.9328134,36.2402534 39.1633188,37.9328134 37.0037508,37.9328134 L29.8600006,37.9328134 C29.268193,37.9328134 28.7884381,37.4530585 28.7884381,36.8612509 C28.7884381,36.2694432 29.268193,35.7896883 29.8600006,35.7896883 L37.0037508,35.7896883 C38.0004902,35.7896883 38.7896883,35.0348032 38.7896883,34.1279899 L38.7896883,8.16201098 C38.7896883,7.25519774 38.0004902,6.50031257 37.0037508,6.50031257 L11.2862501,6.50031257 C10.2895107,6.50031257 9.50031257,7.25519774 9.50031257,8.16201098 L9.50031257,34.1279899 C9.50031257,35.0348032 10.2895107,35.7896883 11.2862501,35.7896883 L18.4300003,35.7896883 Z" fill="#1073DE" fill-rule="nonzero"></path>
    </g>
</svg>

</code>

**Comment by dede-pon** [comment]
Custom icon code :

<pre><code>
<?xml version="1.0" encoding="UTF-8"?>
<svg width="48px" height="48px" viewBox="0 0 48 48" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <path d="M27.5463535,19.3138534 C27.9648247,18.8953822 28.6433005,18.8953822 29.0617717,19.3138534 C29.4802429,19.7323246 29.4802429,20.4108005 29.0617717,20.8292717 L24.7755216,25.1155218 C24.3570504,25.533993 23.6785746,25.533993 23.2601034,25.1155218 L18.9738532,20.8292717 C18.555382,20.4108005 18.555382,19.7323246 18.9738532,19.3138534 C19.3923244,18.8953822 20.0708003,18.8953822 20.4892715,19.3138534 L24.0178125,22.8423944 L27.5463535,19.3138534 Z" fill="#1073DE" fill-rule="nonzero" transform="translate(24.017812, 22.214688) rotate(-180.000000) translate(-24.017812, -22.214688) "></path>
        <path d="M22.9300003,21.0715625 C22.9300003,20.4797549 23.4097552,20 24.0015628,20 C24.5933705,20 25.0731254,20.4797549 25.0731254,21.0715625 L25.0731254,42.5028131 C25.0731254,43.0946207 24.5933705,43.5743756 24.0015628,43.5743756 C23.4097552,43.5743756 22.9300003,43.0946207 22.9300003,42.5028131 L22.9300003,21.0715625 Z" fill="#1073DE" fill-rule="nonzero"></path>
        <path d="M18.4300003,35.7896883 C19.0218079,35.7896883 19.5015628,36.2694432 19.5015628,36.8612509 C19.5015628,37.4530585 19.0218079,37.9328134 18.4300003,37.9328134 L11.2862501,37.9328134 C9.1266821,37.9328134 7.35718751,36.2402534 7.35718751,34.1279899 L7.35718751,8.16201098 C7.35718751,6.04974755 9.1266821,4.35718751 11.2862501,4.35718751 L37.0037508,4.35718751 C39.1633188,4.35718751 40.9328134,6.04974755 40.9328134,8.16201098 L40.9328134,34.1279899 C40.9328134,36.2402534 39.1633188,37.9328134 37.0037508,37.9328134 L29.8600006,37.9328134 C29.268193,37.9328134 28.7884381,37.4530585 28.7884381,36.8612509 C28.7884381,36.2694432 29.268193,35.7896883 29.8600006,35.7896883 L37.0037508,35.7896883 C38.0004902,35.7896883 38.7896883,35.0348032 38.7896883,34.1279899 L38.7896883,8.16201098 C38.7896883,7.25519774 38.0004902,6.50031257 37.0037508,6.50031257 L11.2862501,6.50031257 C10.2895107,6.50031257 9.50031257,7.25519774 9.50031257,8.16201098 L9.50031257,34.1279899 C9.50031257,35.0348032 10.2895107,35.7896883 11.2862501,35.7896883 L18.4300003,35.7896883 Z" fill="#1073DE" fill-rule="nonzero"></path>
    </g>
</svg>
</code></pre>

**Comment by dede-pon** [comment]
Here's the icon : 
[icon-upload.zip](https://github.com/NationalBankBelgium/stark/files/3002916/icon-upload.zip)

**Comment by christophercr** [comment]
@dede-pon in fact, if an SVG already has a viewBox set then it is resizable. The purpose of the `starkSvgViewBox` is to add the viewBox only if the SVG does not have such attribute (otherwise it cannot be resized via CSS).

I tested on my side and I can confirm that the icon you provide can be resized just with CSS as follows:

```css
/* 
    make sure to add the 'mat-icon' in the selector otherwise the 
    default 'mat-icon' rule from Angular Material takes precedence
*/
.mat-icon.some-class {  /* or  mat-icon.some-class also works */
  height: 120px;
  width: 120px;
}
```

Could you please double check if this works for you?

**Comment by dede-pon** [comment]
Hello,

I confirm that you can resize the icon using CSS.

I just pointed out that the svg's initial viewBox isn't changed. If you consider it to be a normal behavior, you can close the issue ;-).

**Comment by christophercr** [comment]
What do you think @cnomes?

**Comment by cnomes** [comment]
@dede-pon I would suggest not using this directive on the icon you provided since it already has (a correct) viewBox set. But I did change the functionality of `starkSvgViewBox` to overwrite the viewBox of an svg if it is already set.
