### ISSUE TITLE
stark-all: remove starkSvgViewBox directive since @mdi/angular-material now includes viewBox in svg icons

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1245]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
[X] Refactor of the code
</code></pre>

## Current behavior

We use `starkSvgViewBox` everytime we use an svg icon in the showcase to add a viewBox on it.

## Expected behavior

Now MaterialDesignIcons added a viewBox in the definition of the svg icons, we should have a look and see if our directive `starkSvgViewBox` is still useful.
See https://github.com/Templarian/MaterialDesign-Angular-Material/pull/6 for more info.

## What is the motivation / use case for changing the behavior?

Clean the code if possible 😊

**Comment by christophercr** [comment]
I agree that using the `starkSvgViewBox` directive in the Stark components will become useless once that fix is released.

However, I do think that the `starkSvgViewBox` is still relevant for those cases where the SVG used doesn't have a viewBox attribute. For example #1216 is about a different SVG being used (although the issue described there is not valid 😋)

**Comment by Templarian** [comment]
Just a heads up `3.6.95` merges this into a release for `@mdi/angular-material`. 😃
