### ISSUE TITLE
ui: table - add option to display "itemsPerPage" in the pagination of the table

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1248]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

There is no way for a user to change the number of items per page when he uses the table component.

## Expected behavior

We should add an option to let the developer give the ability to his users to change the number of items per page.

## What is the motivation / use case for changing the behavior?

Improvement

**Comment by nicanac** [comment]
Hi @SuperITMan ,
I've a question about this issue, should we only had the drop down to select the number of items set by the developers ? Or also add an input to let the user set the exact number of items ?
Nico
