### ISSUE TITLE
ui: date-picker - wrong display in Microsoft Edge

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1333]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Wrong display in Microsoft Edge.

![image](https://user-images.githubusercontent.com/10333565/59332401-66707400-8cf6-11e9-93c6-08712474cdec.png)

In Chrome, it's like this:

![image](https://user-images.githubusercontent.com/10333565/59332424-75efbd00-8cf6-11e9-9866-e11a220da2b4.png)

## Expected behavior

The displaying should be the same in Edge than in Chrome

## Environment

<pre><code>
Angular version: 7.x
Stark version: 10.0.0-beta.8

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X] Edge version 41.16299.1004.0
 

</code></pre>

**Comment by carlo-nomes** [comment]
Similar issues:
https://github.com/angular/components/issues/11650
https://github.com/angular/components/issues/13322

This is no longer an issue in the latest version of Edge (18).
I do not think I am able to make this fix only for the breaking version (17) so I believe it is best to not fix.

**Comment by carlo-nomes** [comment]
Similar issues:
angular/components#11650
angular/components#13322

This is no longer an issue in the latest version of Edge (18).
I do not think I am able to make this fix only for the breaking version (17) so I believe it is best to not fix.
