### ISSUE TITLE
showcase: header not correctly displayed on Safari

### ISSUE THREAD

**Issue by christophercr** [NationalBankBelgium/stark#1338]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When opening the Showcase (https://stark.nbb.be/showcase/latest/home) in Safari, the header is not displayed correctly, just a big blank space instead.

<img width="1414" alt="AppHeader issue on Safari" src="https://user-images.githubusercontent.com/5698318/59697487-2f1a2f80-91ee-11e9-823c-08f51466b4b7.png">

## Expected behavior

The Showcase should be displayed correctly in all evergreen browsers.

## What is the motivation / use case for changing the behavior?

Cross-browser compatibility

## Environment

<pre><code>
Angular version: 7.2.15
Stark version: 10.0.0-beta.8

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version 12.1.1
</code></pre>

**Comment by SuperITMan** [comment]
Re-open this since it's still happening on iOS (iPad & iPhone)

iPhone 8:
![image](https://user-images.githubusercontent.com/10333565/73457077-5edc0900-4373-11ea-8309-50c4ffac00ba.png)

iPad Pro 12' 2018:
![image](https://user-images.githubusercontent.com/10333565/73457177-8e8b1100-4373-11ea-8ede-f4ff2bf97407.png)
