### ISSUE TITLE
ui: table - filtering columns does not affect 'select all'

### ISSUE THREAD

**Issue by carlo-nomes** [NationalBankBelgium/stark#1392]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When filtering a column of the stark-table and checking the select all checkbox all items in the set are included.

## Expected behavior

Only the items shown (valid after filter) should be selected.

## What is the motivation / use case for changing the behavior?

Behaviour is expected by end user.

**Comment by christophercr** [comment]
@carlo-nomes can you elaborate a bit more on this? Is it a visual issue? or how do you get those items?

**Comment by carlo-nomes** [comment]
The easiest way to see the issue is on the select example of the [demo](https://stark.nbb.be/showcase/latest/demo-ui/table), when you filter the id column with 22 there is just 1 item left. Then you check the checkall checkbox (from the header) and remove the filter. You can see that all items are selected.

The eventemitter also emits all items of the list even when a column filter is applied. For my use case this means I can't tell what items the user actually wanted to be selected.

Is this clearer? 😕
