### ISSUE TITLE
starter: typo in git command under the 'installing' section in README.md

### ISSUE THREAD

**Issue by nicanac** [NationalBankBelgium/stark#1414]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
In the `README.md` of the Starter, [the git command to clone stark has a typo](https://github.com/NationalBankBelgium/stark/tree/10.0.0-rc.1/starter#installing) 
`NationalBankBelgum` should be `NationalBankBelgium` (with "i").
```
git clone --depth 1 https://github.com/NationalBankBelgum/stark.git
```

## Expected behavior
```
git clone --depth 1 https://github.com/NationalBankBelgium/stark.git
```

**Comment by christophercr** [comment]
The same typo is present in the [`README.md` of the Showcase](https://github.com/NationalBankBelgium/stark/tree/10.0.0-rc.1/showcase#installing)
