### ISSUE TITLE
ng cli support

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#146]
Can we support the CLI on the starter (and how far can that support go)?

**Comment by ncedric** [comment]
For Scaffolding, everything but guard could be generated by ng cli. Guard CAN be generated but WON'T be used because we are not using angular router.

**Comment by dsebastien** [comment]
We should:
* [ ] add the ng script in the starter to easily execute the cli against it
* [ ] document what we support / don't support with the CLI in the starter's readme

**Comment by dsebastien** [comment]
See list of schematics here: https://github.com/angular/angular-cli/tree/master/packages/schematics/angular

**Comment by dsebastien** [comment]
Interesting ref: https://dev.to/meltedspark/customizing-angular-cli-6-buildan-alternative-to-ng-eject-1oc4?utm_campaign=NG-Newsletter&utm_medium=email&utm_source=NG-Newsletter_264

**Comment by christophercr** [comment]
Closed in #1148
