### ISSUE TITLE
build: provide a way to set the base href

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#148]
Add a way to customize the base href value easily

With this: BaseHrefWebpackPlugin: https://www.npmjs.com/package/base-href-webpack-plugin
We could pass the value to use as an input parameter to the cmd line

Corresponding internal issue: NG-1725

**Comment by SuperITMan** [comment]
For CSS part, we should include PostCSS plugins settings from NG Cli which include config for base path in url in CSS properties

**Comment by dsebastien** [comment]
Ideally we should support the angular cli `ng build` command (@SuperITMan: do we already?), and its `--base-href` flag: https://stackoverflow.com/questions/38112891/angular-2-4-5-set-base-href-dynamically

**Comment by dsebastien** [comment]
In addition, we should also configure this via the ng cli config file as shown here: https://github.com/angular/angular-cli/issues/6477

**Comment by dsebastien** [comment]
@christophercr can you write some docs for this feature?

**Comment by christophercr** [comment]
Sure, I've created a PR for that (#385)
