### ISSUE TITLE
all: lodash - switch from CommonJS imports to ES2015 imports

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#150]
Currently, we should import Lodash like this to include only those functions we need in our bundles:

```
const _cloneDeep: Function = require("lodash/cloneDeep");
```

This means that Lodash cannot be "scope hoisted" because of the CommonJS import. Moreover, it cannot be tree-shaked for the same reason.
We should instead use ES6 imports:

```
import * as _ from "lodash"; // or import _ from "lodash";
// and then use the lodash functions like this:
_.cloneDeep(...);
```

To make this work, babel-plugin-lodash and lodash-webpack-plugin could be used together.
In fact, a major version of Lodash is planned for 2018 in order to support refined entry points to allow "cherry picking" and work together with babel-plugin-lodash

**Comment by dsebastien** [comment]
Comment from @christophercr :
Another loadet to look at:
https://github.com/efidiles/lodash-ts-imports-loader

Interesting article describing different possible solutions:
https://medium.com/@martin_hotell/tree-shake-lodash-with-webpack-jest-and-typescript-2734fa13b5cd

**Comment by cnomes** [comment]
Also investigating the usage of `@types/lodash`.
