### ISSUE TITLE
all: upgrade to Angular 10

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1615]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Stark is running on Angular 7

## Expected behavior

Stark should be running on Angular 10

## What is the motivation / use case for changing the behavior?

Improvement - Update

## Other

This issue will be used to list the different changes we have to do in Stark to make this working well with Angular 8.

**Comment by christophercr** [comment]
I'm a bit confused... is the plan to upgrade to Angular 8, Angular 10 or Angular 11?
Cause in https://github.com/NationalBankBelgium/stark/blob/master/docs/MIGRATION_GUIDE_STARK_11.md it is mentioned Angular 11.

**Comment by SuperITMan** [comment]
Closed by #2901
