### ISSUE TITLE
ui: update mdi/angular-material dependency came with breaking changes

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1762]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Due to upgrade of `@mdi/angular-material` dependency #1706 some icon names changed and it breaks applications.

ie: `github-circle` has been renamed to `github` https://github.com/Templarian/MaterialDesign/issues/4823

![image](https://user-images.githubusercontent.com/10333565/77454554-9655b780-6df0-11ea-89ff-b6e76bd9108b.png)

## Expected behavior

This change should be communicated with teams using Stark 10 and should be documented somewhere. 

The full list of changes is available on https://github.com/Templarian/MaterialDesign/issues/4901 

## What is the motivation / use case for changing the behavior?

Communication / Fix Showcase

**Comment by christophercr** [comment]
@SuperITMan another solution would be to simply revert this change and stick to the 4.9.xxx version.

For me any option is fine

**Comment by SuperITMan** [comment]
@christophercr I thought this change was included in the release 10.0.0. 
Since it is not the case, I think you're right. We should revert this change and maybe keep it for the next major release 😊 (Angular 8).
Like this, we can add the necessary information in the CHANGELOG

**Comment by SuperITMan** [comment]
Btw, after investing a bit more, I found the official CHANGELOG: https://dev.materialdesignicons.com/changelog 
Good to know for the next updates
