### ISSUE TITLE
build & starter: review linting config

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#18]
Review / finalize our tslint config:
* [x] currently we have codelyzer in our deps (from Angular starter) and two different tslint config files (root & starter/). We should clean this up and decide if we keep codelyzer or not
* [x] tslint config files should be present in all parts (root, stark packages, starter) (extends)
* [x] contents of the tslint config should be fully reviewed
* [x] pcss code should also have dedicated configs in each part with the same logic as for prettier & tslint)

If we drop it we'll need to adapt the project's readme

**Comment by dsebastien** [comment]
We'll use codelyzer, it needs to be properly introduced at all levels (root, packages, starter)

**Comment by tenretC** [comment]
To do : 
Update the version of the [stylelint-config-prettier](https://github.com/shannonmoeller/stylelint-config-prettier/) package when my PR for this project is merged and the new version is published on Npm
