### ISSUE TITLE
showcase: add demo for Angular Material steppers

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#199]
In the previous versions of Stark, because there was no Stepper component provided by Angular Material, we encouraged to use [angular-material-steppers](https://github.com/marcosmoura/angular-material-steppers) so Stark provided just an abstract controller to make the manipulation of Steppers a bit easier.

Luckily, there is now a [Stepper component available in Angular Material 2](https://material.angular.io/components/stepper/examples). So we just need to advice the developers on how to use it.

We should:
- implement a nice demo in the showcase 
- write some docs about how to use them in our dev guide (if needed)
- update the API changes doc in Confluence to explain the fact that Stark does not provide this feature anymore and a small migration guide.

**Comment by dsebastien** [comment]
Comment from @christophercr

Interestingly enough, a guy has implemented yet another material-steppers component which supports the vertical layout.
Perhaps we should give it a try:
https://github.com/eberlitz/material-steppers
http://eberlitz.github.io/material-steppers/demo/

**Comment by christophercr** [comment]
Perhaps we don't need to implement a demo page for Steppers after all if we just advice developers to use the [Stepper component available in Angular Material 2](https://material.angular.io/components/stepper/examples). What do you think @SuperITMan @cnomes?

Of course, we should update the API changes doc in Confluence to explain the fact that Stark does not provide this feature anymore and a small migration guide.

**Comment by cnomes** [comment]
@christophercr, I agree.

**Comment by christophercr** [comment]
@nicanac @SuperITMan could you guys take care of this one? Basically adapt the API changes doc in Confluence providing a small migration guide.

So in fact, this issue can be closed cause no changes are needed in Stark ;)

**Comment by nicanac** [comment]
> @nicanac @SuperITMan could you guys take care of this one? Basically adapt the API changes doc in Confluence providing a small migration guide.
> 
> So in fact, this issue can be closed cause no changes are needed in Stark ;)

Yes sure, I'll do it this week, thanks

**Comment by SuperITMan** [comment]
@nicanac any news about this ? :blush: 
Maybe you can create a task in JIRA and we can close this one. What do you think?
