### ISSUE TITLE
ui: route search component

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#207]
Integrate the "route search" component.

This component should have an input field and a search button, that provides auto completion for routes in the application. Once a route is selected, the app navigates to that route.

That component should have two display modes:
* [ ] one just like we have currently on the homepage of Cash
* [ ] one for displaying it in a more compact way in the header. It should display a Search icon by default and clicking on it should animate the display of the search field

**Comment by christophercr** [comment]
@Mallikki these are some ideas for the search component 😉 

https://material.io/design/navigation/search.html#expandable-search
https://teradata.github.io/covalent/#/components/search
