### ISSUE TITLE
admin: add badges

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#23]
Add the following badges (edit to see links)
* [ ] npm version
* [ ] downloads
* [ ] Travis
* [ ] Coveralls (#249)
* [ ] BrowserStack (#274)
* [ ] Dependencies up to date

[![NPM version](https://img.shields.io/npm/v/generator-modern-web-dev.svg)](https://www.npmjs.com/package/generator-modern-web-dev)
[![Downloads](https://img.shields.io/npm/dm/generator-modern-web-dev.svg)](https://www.npmjs.com/package/generator-modern-web-dev)
[![Coverage Status](
https://coveralls.io/repos/dsebastien/modernWebDevGenerator/badge.svg?branch=master&service=github
)](
https://coveralls.io/github/dsebastien/modernWebDevGenerator?branch=master
)

**Comment by christophercr** [comment]
@dsebastien I think this issue can be closed right? I think all the badges are already added...
