### ISSUE TITLE
ci: travis-ci fails because of stranger error in starter

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#2488]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

No Travis-CI build passes because of an error with Starter

## Expected behavior

All builds in Travis-CI should pass when there is no error 😊

## Minimal reproduction of the problem with instructions

Install Stark and starter, then try to execute test in Starter. If doing it in DEBUG mode (in Karma), it will be blocked on following line:
```
DEBUG [es6-transform.karma-typescript]: Transforming C:\LocalData\GEORGAL\DEV\github\stark\starter\node_modules\lodash-es\lodash.js
```

## Environment

<pre><code>
Angular version: 7.x
Stark version: 10.1.0

For Tooling issues:
- Node version: 10 & 12 (npm 6.9.2)
- Platform:  Mac, Linux and Windows

Others:

</code></pre>

**Comment by christophercr** [comment]
@SuperITMan I guess this can now be closed since this is now obsolete due to https://github.com/NationalBankBelgium/stark/pull/2535 right?

**Comment by SuperITMan** [comment]
Indeed, this task is now obsolete.
