### ISSUE TITLE
core: update code to take benefit of new features in ngrx dependencies

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#2551]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## What is the motivation / use case for changing the behavior?

With upgrade to Angular 8, we also upgrade the following dependencies to v8.6.1:
- `@ngrx/effects`
- `@ngrx/store`
- `@ngrx/store-devtools`

This upgrade comes with some nice new features as described in [`@ngrx/platform` CHANGELOG](https://github.com/ngrx/platform/blob/master/CHANGELOG.md#800-2019-06-06).

We should pay attention the CHANGELOG and adapt Stark code to implement new features.

## Environment

<pre><code>
Angular version: 8.x
</code></pre>

**Comment by christophercr** [comment]
@SuperITMan maybe you can take the chance to solve https://github.com/NationalBankBelgium/stark/issues/1340 with these changes 😉

**Comment by SuperITMan** [comment]
Closed by #2636
