### ISSUE TITLE
starter : align starter with the new version 8 of angular

### ISSUE THREAD

**Issue by nicanac** [NationalBankBelgium/stark#2565]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Actually the starter is not align with the latest version of angular(8) supported by Stark.

## Expected behavior

Align the code to suite the requirements of angular 8 
The work can be based on the changes done in the showcase.

**Comment by SuperITMan** [comment]
Closed by #2571
