### ISSUE TITLE
core: all - use RxJS latest and pipeable operators

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#258]
Goal: upgrade to the latest and greatest and try to take advantage of pipeable operators to improve our build size

Pipeable (also called "lettable") operators have been introduced in RxJS 5.5.0 and they provide a new way of composing observable chains.

Moreover, this new approach is more friendly with bundlers such as Webpack in order to automatically tree-shake the unused operators rather than being the developer manually taking care of not importing any operator that is not really needed.

We should move in this direction in order to get all the benefits of tree-shaking once we leverage it in Stark.

See https://blog.angularindepth.com/rxjs-understanding-lettable-operators-fe74dda186d3

Cfr
* https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md
* https://blog.angularindepth.com/rxjs-understanding-lettable-operators-fe74dda186d3

**Comment by dsebastien** [comment]
This is critical for us to be able to tree shake our bundles correctly.
See https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

While doing this we should:
* [ ] get rid of our old RxJS operator imports
* [ ] update packages/rollup.config.common-data.js to remove the obsolete globals

**Comment by dsebastien** [comment]
Comment from @christophercr :
Apparently there is an issue when using the pipeable operators together with Scope Hoisting enabled (see ReactiveX/rxjs#2981).
Perhaps we should wait until the new major version of RxJS (v 6.0) is released to see if this is solved

**Comment by dsebastien** [comment]
One more reason to move forward with this: ReactiveX/rxjs#3212

**Comment by christophercr** [comment]
Closed by #373
