### ISSUE TITLE
Import ng-idle-core and ng-idle-keepalive packages 

### ISSUE THREAD

**Issue by Mallikki** [NationalBankBelgium/stark#261]
## Current behavior
The ng-idle-core and ng-idle-keepalive packages are not yet installed on the new project. 

## Expected behavior
The previous project implemented those packages itself. 
Should we import the available package from @ng-idle/core and @ng-idle/keepalive
or implemented these as we did in the previous app?

**Comment by Mallikki** [comment]
I've created a pull request with those changes

**Comment by tenretC** [comment]
I think you can close this issue : #303
