### ISSUE TITLE
build: configure BrowserStack

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#274]
Goal: automate some UI tests on different devices.

We could make use of their open source offering:
https://www.browserstack.com/contact?ref=open_source&product=combined#open-source

* [x] define config
* [x] evaluate how to automate
* [x] automate
* [ ] document
* [x] integrate with protractor: https://www.browserstack.com/automate/protractor and example: https://github.com/browserstack/protractor-browserstack
* [ ] update CONTRIBUTING.md -> how to configure credentials...
* [x] integrate with Travis (! browserstack credentials as env variables)
* [x] once built once using protractor, make sure the project appears on the BrowserStack page
* [x] add badge: https://www.browserstack.com/automate/status-badges

**Comment by dsebastien** [comment]
Mail sent

**Comment by dsebastien** [comment]
Sébastien & Alexis have access to the BrowserStack config. Can be extended to others later on

**Comment by dsebastien** [comment]
Added environment variables to travis config:
* BROWSERSTACK_ACCESS_KEY
* BROWSERSTACK_USERNAME

**Comment by dsebastien** [comment]
Each dev on the project that wants Travis + BrowserStack support should add the variables above to the travis config for their fork

**Comment by christophercr** [comment]
@cnomes I just came across this article [Using Jest matchers in Cypress](https://medium.com/@NicholasBoll/using-jest-matchers-in-cypress-5e8e7281f5dd) although it is about Jest, it also says:

> This technique could also be applied to using Jasmine’s expect as well.

So maybe you can do the same for Jasmine, I think you would need to use [jasmine-core](https://www.npmjs.com/package/jasmine-core) for this.

**Comment by christophercr** [comment]
The documentation in the Contributing guide will be tackled in #946
