### ISSUE TITLE
CSP directive removed from chrome : plugin-types

### ISSUE THREAD

**Issue by Dedepon** [NationalBankBelgium/stark#2742]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When launching a stark application on the latest version of chrome, we get this error in the console :

The Content-Security-Policy directive 'plugin-types' has been removed from the specification. If you want to block plugins, consider specifying "object-src 'none'" instead.

## Expected behavior

No error should be present

## Minimal reproduction of the problem with instructions

Launch any application with the latest chrome version.

## What is the motivation / use case for changing the behavior?

Best not having error in the console (and replace the disabled csp directive)

## Environment

<pre><code>
Angular version: 8
Stark version: 10.2

Issue should still be present as the csp directive is set in https://github.com/NationalBankBelgium/stark/blob/master/packages/stark-build/config/webpack.config.js : 38

Browser:
- [x] Chrome (desktop) version 90.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by SuperITMan** [comment]
Closed by #3088
