### ISSUE TITLE
showcase & api docs: publish to github pages

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#282]
Build & deploy the showcase and api docs to github pages when creating releases

Preparation:
* [x] enable gh-pages for stark
* [x] create a `gh-pages` branch
* [x] clean the `gh-pages` branch (should start empty)
* [x] create the `api-docs` and `showcase` folders in that branch
* [x] create the `api-docs\stark-core\latest` and `api-docs\stark-ui\latest` folders
* [x] create a `latest` folder in showcase
* [x] create the showcase app based on starter: #353 
* [x] adapt the .travis.yml to also generate the prod build of the showcase
  * added a new script: `npm run build:showcase`

Then create a script (gh-deploy.sh) executed as part of the Travis CI build that will...

First perform checks:
* [x] checks if the build occurs on the main Stark repository and not on a fork); IF NOT then it exits (0)
* [x] checks if the build occurs on the correct node version (we don't want to publish docs for each version of node we test against); IF NOT then it exits (0)
* [x] checks if the build occurs for a PR; IF SO, then it exits (0)
* [x] checks if the build is for a release; IF NOT then it exits (0)
* [x] checks that the necessary decryption keys for the SSH private key are available as environment variables (necessary to be able to push our changes to GitHub!)

Then generate the API docs
* `npm run docs:all`

The prepare the docs for upload to the github-pages branch:
* [x] identifies the version the build is executed for
* [x] ensures that the identified version matches the version in stark/showcase/package.json; IF NOT then if fails (-1) because it means that the showcase hasn't been updated for the release
* [x] creates the `showcase/<version>` folder
* [x] copies the showcase build output to `showcase/<version>`
* [x] copies the showcase  build output to `showcase/latest`

In addition, for each stark module:
* [x] creates the `api-docs/<stark-module>/<version>` folder
* [x] generates the api-docs for the module and copies the output to `api-docs/<stark-module>/<version>`
* [x] copies the api-docs to `api-docs/<stark-module>/latest`

Finally:
* [x] adds, commits and pushes the changes to the gh-pages branch to github
* [ ] question: how will we mock the back-end with GitHub pages?

Docs:
* [x] document the key generation / configuration
  * see last comments

Bonus
* [x] create a DNS CNAME record to nbb.be (e.g., opensource.nbb.be) and make it point to `https://nationalbankbelgium.github.io`
  * opensource.nbb.be created
* [x] define the custom domain on Stark's repository
* [x] enable HTTPS for the custom domain (need to wait for the certificate to be ready)
* [ ] create a homepage and add a link to Stark docs: opensource.nbb.be/stark/api-docs/showcase/latest`

Refs:
* https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
* https://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci
* https://www.npmjs.com/package/angular-cli-ghpages
* https://github.com/angular-schule/angular-cli-ghpages/wiki/FAQ
* enable: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/
* https://github.com/domenic/zones/blob/master/deploy.sh

**Comment by dsebastien** [comment]
Alternative: deploy to Firebase (?): https://scotch.io/tutorials/deploying-an-angular-cli-app-to-production-with-firebase

**Comment by dsebastien** [comment]
Blocked by #148

**Comment by dsebastien** [comment]
Alternative option for deployment to gh-pages for simpler projects: https://docs.travis-ci.com/user/deployment/pages/

**Comment by dsebastien** [comment]
@christophercr just thought about this, but so far we didn't think about the distinction between stark-core and stark-ui api docs.. I guess each needs its own sub-folder under api-docs?

So the structure would be like:
```
| api-docs
|-- stark-core
|---- <version>
|-- stark-ui
|---- <version>
```

**Comment by dsebastien** [comment]
Docs publication currently blocked by #127

**Comment by dsebastien** [comment]
Showcase publication currently blocked by #353

**Comment by christophercr** [comment]
@dsebastien indeed, we overlooked that. I agree with the folder structure you propose ;)

**Comment by dsebastien** [comment]
Okay, proposal adapted!

**Comment by dsebastien** [comment]
I'll adapt the proposal to match our last discussion:
* we'll generate a repo-specific SSH keypair for Stark
* we'll associate the public key with Stark: this is called a deploy key on github: https://developer.github.com/v3/guides/managing-deploy-keys/
* we'll encrypt the private key with travis-cli (https://www.npmjs.com/package/travis-cli): `travis encrypt-file mysuperprivatekey`
* we'll store the necessary decryption material inside the Travis CI config (protected vars)
* we'll store the encrypted private key in the sources
* we'll decrypt the key in the CI, paying attention not to leak it out :p
* we'll use it to clone/push using ssh

**Comment by dsebastien** [comment]
GH repos are limited to ~1GB and stark-core's API docs alone is ~25MB, so our initial idea of also keeping API docs for nightly builds will not hold for long.

I'll only allow releases to get their published docs.
