### ISSUE TITLE
stark-build: add circular-dependency-plugin

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#315]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Code can contain circular dependencies

## Expected behavior

No circular dependency.

## What is the motivation / use case for changing the behavior?

Avoid circular dependencies.

**Comment by christophercr** [comment]
Closed by #400
