### ISSUE TITLE
build: document stylesheets processing

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#33]
What we have for now: a bit of docs (not up to date nor correct in starter/README.md)
What we want:
* [ ] explanation about how stylesheets are loaded
* [ ] explanation about how stylesheets are processed/bundled... (webpack, TS, ...)
* [ ] explanation about the differences in processing/bundling between dev and prod)

This doc can be put in the starter's readme for now

**Comment by dsebastien** [comment]
For now, blocked by #114

**Comment by SuperITMan** [comment]
Obsolete since we are using NG CLI to build our application
