### ISSUE TITLE
build: add SonarTS checks to our current TSLint checks

### ISSUE THREAD

**Issue by christophercr** [NationalBankBelgium/stark#331]
Sonar checks for TS with TSLint!  Now that Stark is an open source project which anyone can contribute to, I think this is definitely something we should add:

https://github.com/SonarSource/SonarTS

What do you think? @dsebastien @SuperITMan @ncedric @RobbyDeLaet 

If you agree, I will submit a PR for this ;)

**Comment by dsebastien** [comment]
Great idea indeed
