### ISSUE TITLE
Rewrite the Commit Message Guidelines in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tenretC** [NationalBankBelgium/stark#338]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>
Rewrite the Commit Message Guidelines in CONTRIBUTING.md to match the configuration applied for Commitlint ?
See #339 for the `Commitlint` rules

**Comment by dsebastien** [comment]
Good idea, go ahead
