### ISSUE TITLE
Add validation for .ng-cli-config.json based on json schema

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#342]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## What is the motivation / use case for changing the behavior?

When packages are made, a script should validate that the .ng-cli-config.json in each package is valid based on his linked json schema.

.ng-cli-config.json is present in stark packages for setting assets (to be read later on by Stark-Build) and also the configuration for running tests (to be read by Stark-Testing).

We should be sure that the file is correctly written (based on json schema from Angular CLI) when we build the packages to avoid error when using stark-build with stark-core/stark-ui in an application.

This is needed to improve #341

**Comment by christophercr** [comment]
Can't we simply use the same library angular uses? @ngtools/json-schema'

It is used here for example: https://github.com/angular/devkit/blob/6cc697d163114f2ec1f082420b8d2579ec7fd4f6/scripts/serialize.ts

**Comment by SuperITMan** [comment]
The big question is Where and When ? 😃 
Because I don't have lots of ideas for this.... 😞 
In the build.sh ? In rollup config ? In ...?

**Comment by christophercr** [comment]
Mmm... I would suggest to have a "pre" script in the package.json for the
build, like this:

"prebuild" : "npm run validatePackages.js"

There we check everything we need to validate that the packages are
correctly configured (like the ng-cli-config.json using the json schema)
and if they are invalid we throw an error. That way we fail fast so the
build script will not even be executed.
