### ISSUE TITLE
stark-toast-text not responsive

### ISSUE THREAD

**Issue by RobinGiel** [NationalBankBelgium/stark#3519]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
When the text in the stark-toast-notification is too long it pushes the confirm button out of screen.

## Expected behavior
The textbox should be responsive in order to show the entire message and the confirm button.

**Comment by SuperITMan** [comment]
Closed by #3520
