### ISSUE TITLE
remove the `mkdirp` code in the starter scripts `server:dev` & `build:dev`

### ISSUE THREAD

**Issue by tenretC** [NationalBankBelgium/stark#356]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

There is an issue with the way webpack-monitor generate the folder for its reports.
I'll fix this by adding `npx mkdirp reports` to `server:dev` & `build:dev` scripts, but it should be removed when this issue is fixed.
NB : this only concerns the dev mode (webpack-monitor is only defined in the webpack.dev config)

## Environment

<pre><code>
Angular version: X.Y.Z
Stark version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dsebastien** [comment]
Did you also create an issue on webpack monitor that we could also track for a cleaner fix?

**Comment by tenretC** [comment]
Yes ;)
But thanks to Alexis I've done something much cleaner so I can close this issue
See #358

**Comment by dsebastien** [comment]
Great :)
