### ISSUE TITLE
doc: improve api docs

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#389]
Goal: improve our existing api docs

Tasks
* [x] add scripts to serve/watch the api-docs
* [x] add scripts to check docs coverage
* [x] add missing API docs
* [x] add CI coverage threshold check
* [x] integrate in the demo/showcase

For coverage: https://compodoc.app/guides/documentation-coverage.html

**Comment by christophercr** [comment]
We can enable some TSLint rules to help us with this:

- [completed-docs](https://palantir.github.io/tslint/rules/completed-docs/)
- [jsdoc-format](https://palantir.github.io/tslint/rules/jsdoc-format/)
- [no-redundant-jsdoc](https://palantir.github.io/tslint/rules/no-redundant-jsdoc/)

**Comment by Mallikki** [comment]
Sorry guys, I've made a lot of commit for this first ticket.. Christopher helped me solved this with a rebase, I'll try not to be such a bother next time ;)

The PR for the issue is here: https://github.com/NationalBankBelgium/stark/pull/429

Everything still needs to be reviewed, especially for the starter, as some classes have been taken from other projects, and I wasn't sure what to put there.

**Comment by christophercr** [comment]
In fact, the TSLint rules are indeed for JSDoc, but that is only the format of the comments which at the end is the same that compodoc needs.

The idea here is just to use those TSLint rules that will help us (force us :p) to keep the docs in sync by notifying us even faster than compodoc that we are missing docs.

We can just use the rules we need and don't conflict with compodoc, but in any case they are definitely useful.

**Comment by Mallikki** [comment]
@christophercr I've added the tslint rules, which are working well. I'll just need to know what we should add  for the completed-docs rule. 
If I put all parameters here (classes, methods, interfaces, ...), I'm afraid it will overload the code... 
Compodocs is very specific with documentation (we even have to put comments on top of constructor), and the code itself has lost in readability already. 
Maybe we could try to configurate compodoc a bit more, and then use these TSlint rules in addition to that?
