### ISSUE TITLE
build: integrate custom HMR bootstraping into stark-core

### ISSUE THREAD

**Issue by christophercr** [NationalBankBelgium/stark#412]
Goal: move the custom HMR bootstraping logic into ~~stark-build~~ stark-core.

Currently we just copied the HMR bootstraping from the Angular Class starter.

Document this feature

**Comment by dsebastien** [comment]
Just wondering, but why put the HMR bit in stark build rather than in stark core?
AFAIK, there's also an integration to do with NGRX.

I'll publish my "bootstrap" branch, I started taking that but couldn't move forward with it

**Comment by christophercr** [comment]
Indeed, it should be part of stark-core... so I'll rename this issue ;)

**Comment by christophercr** [comment]
Closed by #486
