### ISSUE TITLE
showcase: fix warnings when running "npm start"

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#434]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

`npm run start:hmr` on showcase create warnings

`System.import() is deprecated and will be removed soon. Use import() instead.`

## Expected behavior

No warnings

**Comment by christophercr** [comment]
The warning about System.import() is a known issue in Angular and it is tracked here: angular/angular#21560

We'll see what the outcome of that issue is ;)

**Comment by christophercr** [comment]
Solved in #1006
