### ISSUE TITLE
ui: theming - move the themes folder from assets

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#457]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Expected behavior
All the SCSS theme files are inside the assets/themes folder. They should be placed somewhere else and not be exported

**Comment by christophercr** [comment]
Closed as it is now obsolete. The themes have been correctly placed in the corresponding Stark UI components.

Now the `assets/themes` folder contains only theming for some Angular Material components such as buttons and cards.
