### ISSUE TITLE
showcase: create the code viewer component

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#459]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Possibility to swith from code to component like in the Angular Material doc.

**Comment by christophercr** [comment]
Closed by #480
