### ISSUE TITLE
docs: published docs are not functional

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#466]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The docs published on GitHub are broken due to two issues:
* [ ] showcase issue: base path is set inside the page, which causes 404 errors because our docs are not at the root "/" as defined in the index.html; see here for an example: https://opensource.nbb.be/showcase/latest
  * we might be able to fix this by changing the base url here: https://github.com/NationalBankBelgium/stark/blob/master/showcase/angular.json
* [ ] https://opensource.nbb.be points directly to Stark, which is not what we want
  * we should request a stark.nbb.be domain name for this project and use opensource.nbb.be for a more general entry point to our oss projects

## Expected behavior
Working docs site with a logical URL :)

**Comment by christophercr** [comment]
Reopened since the final solution is not yet finished :p
