### ISSUE TITLE
release: npm tags "latest" and "next" are not consistent

### ISSUE THREAD

**Issue by christophercr** [NationalBankBelgium/stark#468]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

After releasing a new version of Stark packages, the "latest" and "next" tag are inconsistent: the "next" tag shows a previous version than the "latest". The reason is that the "next" tag is the version generated by the nightly build.

![stark inconsistent npm tags](https://user-images.githubusercontent.com/5698318/41961629-7f2d2254-79e2-11e8-9a95-10498b568b20.PNG)

## Expected behavior

The "next" version should always be higher than the "latest" (or the same right after a new version is released).

## Minimal reproduction of the problem with instructions

Release a new version of Stark and check the versions in NPM.

## Other information
Previously, in Stark 9 we managed this by changing manually the `package.json` to set the next version right after a new release.

However this will not work anymore since we have `release-it` to automate the release process and change the `package.json` with the released version. Moreover, that tool will also "calculate" the version to be released: major, minor or patch version.

So if we change the `package.json` ourselves then:

- we will throw away the automatic version "calculation" that `release-it` does based on the commit history.
- `release-it` will complain the next time we want to release because the version already exists.

**Comment by christophercr** [comment]
As we discussed, maybe an option would be to change the nightly build script to set a version which would be less specific but still meaningful like this:

`10-alpha.4-commitHash`  =>  major version + alpha/beta pre-version if any + commit hash

**Comment by christophercr** [comment]
It happened again on the latest release:


![stark inconsistent npm tags alpha-4](https://user-images.githubusercontent.com/5698318/43443138-4f12be3e-94a0-11e8-8d88-a71d99beebc9.PNG)

**Comment by SuperITMan** [comment]
Linked to #420

**Comment by christophercr** [comment]
Closde in #1185
