### ISSUE TITLE
docs: create entry point for the documentation

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#469]
Goal: define the entry point for the documentation.

Currently we publish our docs on gh-pages: https://github.com/NationalBankBelgium/stark/tree/gh-pages
We publish two things:
* the api-docs: https://github.com/NationalBankBelgium/stark/tree/gh-pages/api-docs
* the showcase: https://github.com/NationalBankBelgium/stark/tree/gh-pages/showcase

Our problem is that we don't have an entrypoint to the docs.
If we go to https://opensource.nbb.be/ we get a 404

We need to:
* [ ] create an index.html page here to redirect to the showcase/latest folder: https://github.com/NationalBankBelgium/stark/tree/gh-pages
* [x] create a CNAME called "stark.nbb.be"
* [x] change the custom domain in the stark repository settings
* [x] add a link to https://stark.nbb.be in the README of the project
* [x] add information in the showcase to provide links to the documentation
  * a link to the latest api-docs for stark-core: https://github.com/NationalBankBelgium/stark/tree/gh-pages/api-docs/stark-core/latest
  * a link to the previous api-docs for stark-core: https://github.com/NationalBankBelgium/stark/tree/gh-pages/api-docs/stark-core
  * a link to the latest api-docs for stark-ui: https://github.com/NationalBankBelgium/stark/tree/gh-pages/api-docs/stark-ui/latest
  * a link to the previous api-docs for stark-ui: https://github.com/NationalBankBelgium/stark/tree/gh-pages/api-docs/stark-ui
  * a link to the previous showcase versions: https://github.com/NationalBankBelgium/stark/tree/gh-pages/showcase

**Comment by christophercr** [comment]
Closed by #518
