### ISSUE TITLE
bootstrap: integrate hmr with ngrx

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#478]
Cfr https://github.com/gdi2290/angular-hmr: there is a configuration step required to integrate HMR and NGRX

**Comment by SuperITMan** [comment]
Thanks for the info, I'm currently working on the integration of HMR into stark-build, see #412 
I'll integrate this in my future PR

**Comment by christophercr** [comment]
@SuperITMan I think @dsebastien is also working on the same PR (as mentioned here https://github.com/NationalBankBelgium/stark/issues/412#issuecomment-401939831), maybe you can coordinate and work together on that?

**Comment by SuperITMan** [comment]
Since we already have ngrx and hmr in Stark, I guess this can be closed 😊
