### ISSUE TITLE
ui: translation - Add Translation support

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#497]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Expected behavior
Integrate the translation support and add it to the existing component (action bar, table, logo, slider)

**Comment by christophercr** [comment]
Closing this issue since is obsolete. The translation support will be added in all components while implementing them.
