### ISSUE TITLE
build: add support for environments

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#50]
Assuming the build specifies the environment (either default value or provided as CLI argument), make sure we have support for finding out the current environment within Stark apps (programmatically)

This requires some cleanup as we currently have (at least) these:
* webpack options
* Define plugin
* src/environments/environments.ts: provides programmatic checks (if env === ...)
* custom-typings.d.ts: probably doesn't need any typings for the env anymore!
* HTML templating
* polyfills.browser.ts

**Comment by christophercr** [comment]
Re-opened this issue since it is not completely solved.

Currently it is not possible to programatically check the current enviroment in the stark packages, only in the client application (i.e. starter or showcase).
