### ISSUE TITLE
ui: matTooltip translation

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#502]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The tooltip is not being translated.

## Minimal reproduction of the problem with instructions
```
<button [matTooltip]="STARK.ICONS.ADD_ITEM" translate mat-raised-button></button>
```

One solution could be to add our own tooltip directive

**Comment by SuperITMan** [comment]
I think we should not create a directive for this but we should the translator library as proposed:

`[matTooltip]={{ 'STARK.ICONS.ADD_ITEM' | translate }}` 

or in the controller:
```typescript
...
public constructor(
    ...,
    private translateSvc: TranslateService
) {}

...

public myTranslatedString: string = this.translateSvc.instant("STARK.ICONS.ADD_ITEM");
```

then in the template, simply do this:
`[matTooltip]=myTranslatedString`
