### ISSUE TITLE
ui: svg viewbox directive - style not applied on scoped SCSS

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#504]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The svg tag inside the mat-icon doesn't reflect its parent scope.

## Expected behavior
We should add the scope to the svg tag

## Minimal reproduction of the problem with instructions
Create a page in the showcase, add an icon button and change the width and height on the scoped SCSS

SCSS:
`
.mat-icon-button {
  .mat-icon svg {
    height: 15px;
    width: 15px;
  }
}
`

HTML:
`
<button mat-icon-button><mat-icon starkSvgViewBox svgIcon="heart"></mat-icon></button>
`

**Comment by cnomes** [comment]
"Fix starksvgviewbox directive"
