### ISSUE TITLE
core: integrate polyfills into stark-core

### ISSUE THREAD

**Issue by christophercr** [NationalBankBelgium/stark#507]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Every single app that wants to use stark need to include the necessary polyfills by himself. The set of polyfills are most of the time the same so this is some extra work that is duplicated.

## Expected behavior

Stark provides the "default" (minimal required) polyfills as it was the case in Stark 9 so there is no need to add them manually to every single app. More polyfills can be added if needed.

## What is the motivation / use case for changing the behavior?

Stark should provide everything what is needed to get an app up and running with the minimal effort.

**Comment by dsebastien** [comment]
Make sure to add the server-sent-events polyfills (if not there anymore)

**Comment by christophercr** [comment]
As discussed together with @SuperITMan and @Mallikki, Stark won't provide the polyfills because these are optional depending of the requirements of the application.

Moreover, polyfills are not "tree-shakeable" because they monkey-patch some Browser implementations, so if we add them in stark-core, every application will have those in the PROD build regardless of whether they are actually needed or not.

Instead, we will just provide a simple guide on how to add polyfills to their app and which ones are the most common in case they want to support Internet Explorer.

**Comment by dsebastien** [comment]
Makes sense. I think that as time passes, the need for many of those polyfills also fades away. At this point, ES2016+ features are pretty well supported by modern browsers: http://kangax.github.io/compat-table/es2016plus/
