### ISSUE TITLE
showcase: table - add a demo page for the table

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#514]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Expected behavior

Add the example viewers to the table page that shows the different feature of the stark table.

**Comment by christophercr** [comment]
Closed in #714
