### ISSUE TITLE
build: automate release process

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#54]
We should have a script that helps us doing a release easily and automatically.
It should
* update package.json (semver)
* update changelog
* tag
* push the tag
* let travis handle the npm publish

First
* [x] review what angular does: https://github.com/angular/angular/tree/master/scripts/release
* [x] evaluate semantic-release
* [x] evaluate standard-version

**Comment by dsebastien** [comment]
Related to #31

**Comment by dsebastien** [comment]
Related to #24: semantic-release follows Angular's commit message guidelines

**Comment by SuperITMan** [comment]
mmm...
It should be :
* set root package.json version
* install
* install:all
* commit package-lock.json

**Comment by dsebastien** [comment]
Second proposal after internal discussion:

Travis pre-reqs:
  * [ ] NPM_TOKEN environment variable
  * [ ] or npm login against official npm registry?

First initiate the release manually through: `npm run release:prepare`; which will
* [ ] make sure there are no local changes
* [ ] update the root package.json version automatically (semantic-release?)
  * that version number will be used as basis in the build to adapt all other package.json files
* [ ] git commit package.json
* [ ] update changelog
* [ ] commit changelog
* [ ] git tag version
* [ ] git push --tags
* [ ] git publish changelog (releases page on GH)

Once done, a Travis build will be triggered. Since there is a tag, it'll do the release which will execute `npm run release:perform` which will:
* clean:all
  * remove node_modules for each package
  * remove package-lock.json for each package
  * remove node_modules at root
  * remove package-lock.json at root
* cache verify
* install:all (root + all modules)
* commit package-lock.json (root + all modules)
* build:all
* publish each module on npm
* announcement
  * twitter
  * internal NBB

**Comment by dsebastien** [comment]
Issue to fix: with the above, once release:perform runs on Travis, we use the resulf ot he previous commands that did `npm run install:all` which also calls `npm run build` but WITHOUT passing the `--publish` option, meaning that the version in the package.json files will contain the last commit hash.

We need figure out how to remove that suffix when doing the release

**Comment by dsebastien** [comment]
Useful angular scripts:

```
angular publish: https://github.com/angular/angular/blob/master/scripts/release/publish
#!/usr/bin/env bash

# Use for PATCH releases
# Publish all packages in `dist/packages-dist` to npm

(cd dist/packages-dist; for p in `ls .`; do npm publish --access public $p; done)



angular publish-next: https://github.com/angular/angular/blob/master/scripts/release/publish-next
#!/usr/bin/env bash

# Use for BETA and RC releases
# Publish all packages in `dist/packages-dist` to npm (as next)

(cd dist/packages-dist; for p in `ls .`; do npm publish --access public --tag next $p; done)



angular pre-check: https://github.com/angular/angular/blob/master/scripts/release/pre-check

#!/usr/bin/env bash

# Verify peer deps constraints and package.json before publishing to npm
# There should be no npm errors

mkdir tmp
cd tmp
npm init -y
npm install --save ../dist/packages-dist/* zone.js@0.8.10 rxjs@6.0.0-beta.1 typescript@2.7
cd ..
rm -rf ./tmp



angular post-check: https://github.com/angular/angular/blob/master/scripts/release/post-check


#!/usr/bin/env bash

# use for PATCH releases
# Verify that all packages are published with correct version:

mkdir tmp
cd tmp
npm init -y
npm install typescript@2.6 rxjs@5.5.0 zone.js@0.8.10 @nationalbankbelgium/{stark-build,stark-core,stark-testing} --save
cd ..
rm -rf tmp

echo "CHECK THE DIST-TAGS"

grep '"name": "@nationalbankbelgium' $(find packages -name package.json) | grep -o '@nationalbankbelgium/[^/"]*' | sort -u | xargs -n 1 -I% npm show \% name dist-tags




angular post-check-next: https://github.com/angular/angular/blob/master/scripts/release/post-check-next



#!/usr/bin/env bash

# use for BETA and RC releases
# Verify that all packages are published with correct version:

mkdir tmp
cd tmp
npm init -y
npm install typescript@2.7 rxjs@6.0.0-beta.1 zone.js@0.8.20 @nationalbankbelgium/{stark-build,stark-core,stark-testing}@next --save
cd ..
rm -rf tmp

echo "CHECK THE DIST-TAGS"

grep '"name": "@angular' $(find packages -name package.json) | grep -o '@nationalbankbelgium/[^/"]*' | sort -u | xargs -n 1 -I% npm show \% name dist-tags

```

**Comment by dsebastien** [comment]
Proposal needs review.
If we use standard-version, then we should let it do bump, changelog, commit AND tag.
If the tag is created and pushed, then the client should also handle the github release page creation.

On Travis
* we should not check the commit message as proposed before, but the fact that the build was triggered by a tag creation
* the package-lock.json files add/commit should be forgotten for now ??

**Comment by dsebastien** [comment]
I've configured the NPM_TOKEN variable in Travis.
NEVER log that token ;-)

**Comment by dsebastien** [comment]
One issue to be aware of: https://github.com/webpro/release-it/issues/273

**Comment by dsebastien** [comment]
For the tags like nightly, dev, beta and the like, we could have additional scripts passing an argument for that
