### ISSUE TITLE
ui: add the timestamp mask to the date-picker and date-range-picker components

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#549]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Expected behavior
Integrate the timestamp mask directive into the date-picker and date-range-picker components

## What is the motivation / use case for changing the behavior?

See #125

**Comment by christophercr** [comment]
Solved in #1232
