### ISSUE TITLE
build: integrate jarvis or similar

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#55]
Goal: evaluate and integrate if worth it (in dev)
https://github.com/zouhir/jarvis

Or similar solutions

**Comment by christophercr** [comment]
Finally we decided to integrate [Webpack Bundle Analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) which is more user friendly and it is [actively mantained by the webpack-contrib team](https://github.com/webpack-contrib/webpack-bundle-analyzer/releases) compared to [Jarvis](https://www.npmjs.com/package/webpack-jarvis).

We did the integration together with the Angular CLI builders via this PR #1148
