### ISSUE TITLE
ui: SCSS - handle line height

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#553]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
Line height have been removed from the body. If the end user set it, it's gonna break the sttle of some angular material components.

## Expected behavior
Angular Material components needs to have a default line height (date picker). In fact the line height should not be defined for those components.
We have to find a way for the component to have the default line height even though the body line height is defined by the end user.

**Comment by christophercr** [comment]
Closed in #672
