### ISSUE TITLE
Showcase: Sidebar menu is not displayed correctly

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#569]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

Sidebar menu is opened besides the content. That makes the content ugly on mobile.

## Expected behavior

Sidebar menu should be opened over the content (like it was the case in the old Stark).

## Minimal reproduction of the problem with instructions

Open [Stark showcase](https://stark.nbb.be/showcase/latest/) and open the menu.

**Comment by christophercr** [comment]
Fixed by #638
