### ISSUE TITLE
build: build-prod is taking too much time

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#572]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When running `npm run build:prod` in showcase, it takes too much and slows down the tests on Travis.

## Expected behavior

This should be faster to and should not slow down the tests on Travis

**Comment by christophercr** [comment]
As discussed with @SuperITMan, we will adapt the Travis config and the webpack prod config:
- we will run the uglification process just once and without sourcemaps for every PR
- we will run the uglification process 3 times and with sourcemaps for every release (on tag branches) and on nightly builds
