### ISSUE TITLE
release: release-it did not upgrade stark version in package-lock.json during the latest release

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#574]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

release-it does not adapt version in package-lock.json

## Expected behavior

release-it should upgrade version in package-lock.json

**Comment by christophercr** [comment]
Apparently we can change the `pkgFiles` option to include the package-lock.json:

https://github.com/webpro/release-it/issues/147
