### ISSUE TITLE
showcase: Remove the tooltip from the ExampleViewer component

### ISSUE THREAD

**Issue by RobbyDeLaet** [NationalBankBelgium/stark#580]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When hovering over the example viewer, it displays the translation key from the title as a tool-tip.
Even when the mouse-pointer is over another component inside the example viewer.

## Expected behavior

Prevent the tool-tip from showing.

**Comment by christophercr** [comment]
Closed by #584
