### ISSUE TITLE
ui: homepage - "no javascript" warning

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#596]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
App just breaks

## Expected behavior
Warning when javascript is disabled. We had this in Stark 9.

**Comment by christophercr** [comment]
Closed in #848

**Comment by christophercr** [comment]
Closed in #848
