### ISSUE TITLE
ui: homepage - outdated browser warning

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#597]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
Nothing specific happens or the app breaks

## Expected behavior
Warning when the browser is considered too old. We had this in Stark 9.

**Comment by cnomes** [comment]
@SuperITMan I included this issue in my pre #848 because it was very similar to two other issues I was working on. I added you as a reviewer.

**Comment by christophercr** [comment]
Closed in #848
