### ISSUE TITLE
showcase: improve

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#598]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The showcase is not well organized and the site as it stands doesn't give a good impression of Stark, doesn't explain what it is, etc.

## Expected behavior
The showcase should be improved on many levels, but we could start with this:
* [x] improve the homepage (order to be determined!)
  * introduction to Stark: what it is
  * links to the main other pages: documentation (components, services, directives, ...), API documentation 
  * link to GitHub project, to travis, etc
(in a table, not with big icons anymore!)
* [x] fix the sidebar bug
* [x] remove the "back" icon in the header 
* [x] fix the logout button (should do something)
* [x] add the translation switcher to the header
* [x] add the footer
* [x] default language set to English
* [x] put the "Stark" name in Pascal case instead of all uppercase as it is now...

Also, the menu should be reorganized as follows:
* Home: point to the current homepage mixed with the news page
* News
* Features:   list of major features / ui components with links to their pages, ...
* Documentation: homepage for the docs
  * Getting started
  * Developer guide: entry point to the content we previously had on our internal wiki
  * UI Components
  * Services
  * Directives
  * API: table with the links we also have on the homepage

**Comment by christophercr** [comment]
Closed in #717
