### ISSUE TITLE
ui: header - Integrate newly implemented components

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#603]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The header contains shapes instead of real stark components.

## Expected behavior
We should add the real component in the header and also adapt the header guidelines
- [x] App Logo
- [x] App logout
- [x] App data
- [x] Language selector

**Comment by christophercr** [comment]
After the App Data component implemented in #936, the components in the header are complete
