### ISSUE TITLE
showcase: language - translate example files to English

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#613]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
Some of the example files contains showcase related translations.

## Expected behavior
In the example files, all translated text starting with `SHOWCASE.` should be replaced by english texts.

**Comment by christophercr** [comment]
Closed in #736
