### ISSUE TITLE
ui: @Output - Interfaces

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#614]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
Some emitted events are not defined by an interface.

## Expected behavior
We should define interfaces for all emitted events, based on what Angular Material is doing.

**Comment by SuperITMan** [comment]
Obsolete
