### ISSUE TITLE
ui: dropdown - add full width mode

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#640]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
In the app language selector, the dropdown doesn't take the size of its parent container. Its width remains 180px.

## Expected behavior
We should add a class to the dropdown components so it can fill its parent width.

**Comment by christophercr** [comment]
Closed by #665
