### ISSUE TITLE
Move some imports from showcase to stark-ui

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#641]
Currently, we import the following styles in showcase only (styles.scss)
```scss
@import "~normalize.css/normalize.css";
@import "~prismjs/themes/prism-okaidia.css";
```
but if we don't import them, that breaks the UI of stark-ui. 
We should move normalize.css import in stark-ui and the import of prismjs in pretty-print component.

**Comment by christophercr** [comment]
Mmm I'm not sure about this.

- "normalize.css" is just a library that @catlabs found useful to make the styling easier and faster, so I don't think this should be provided by Stark itself as it is just a developer's choice in their app.
- "prism-okaida" is the theme we suggest for the PrettyPrint component, again a developer's choice. Moreover, I don't think is possible to use more than one prismjs theme files and that the last one to be imported will override the rest. By the way, Robby is working on this PR #513 to document this.

**Comment by christophercr** [comment]
Ok, as discussed, we will only move `normalize.css` to Stark UI dependencies and import it in `packages/stark-ui/assets/styles/_base.scss` so the apps should not import it anymore. 😉
