### ISSUE TITLE
showcase: example-viewer - No animation on show code

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#661]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
When we want to see the code, it expand and then animate the code

## Expected behavior
The code should already be there on open without animations. Animations are only relevant when we switch from one code file to another.

**Comment by christophercr** [comment]
This issue was in fact in the [Angular Material's `mat-tab`](https://material.angular.io/components/tabs/overview) and it was fixed in the [version 7.0.0-beta.0](https://github.com/angular/material2/blob/master/CHANGELOG.md#700-beta0-2018-08-30)

See https://github.com/angular/material2/pull/12549
