### ISSUE TITLE
showcase: margin & padding - Strategy

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#671]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
Inconsistent vertical margins

## Expected behavior
We should find a way to use margins & paddings with consistence. For instance, we could add `<section>` with a `margin-bottom` to improve the UX.

**Comment by christophercr** [comment]
Closed by #672
