### ISSUE TITLE
ui: timestamp-mask-directive - implement component/module

### ISSUE THREAD

**Issue by RobbyDeLaet** [NationalBankBelgium/stark#683]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Expected behavior

Implement the timestamp-mask-directive.

## What is the motivation / use case for changing the behavior?

See #125

**Comment by SuperITMan** [comment]
Closed by #1134
