### ISSUE TITLE
showcase: example-viewer - flex layout

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#700]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The code is too long when displaying `example-viewer` components on the same line. 

## Expected behavior
When the end users click on the code button, the card should take the full width of the `main-container`.
That would improve a lot the button page in the showcase for instance.

It could be nice also to have a transition, see https://material.io/design/components/cards.html#behavior

**Comment by SuperITMan** [comment]
issue has been fixed
