### ISSUE TITLE
ui: table - component style improvement

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#715]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The table has been done before the color and typo work. 

## Expected behavior
SCSS wise some improvements could be done, for instance the font size is too big.

**Comment by christophercr** [comment]
Closed in #746
