### ISSUE TITLE
doc: contributing - explain outputs of the build

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#72]
* FESM2015, FESM5, and UMD formats cfr https://goo.gl/AMOU5G and http://angularjs.blogspot.be/2017/03/angular-400-now-available.html
* creates .d.ts files
* generates Ahead-of-Time metadata (metadata.json): https://angular.io/guide/aot-compiler#why-do-aot-compilation

**Comment by christophercr** [comment]
link already mentioned in the README
