### ISSUE TITLE
ui: footer - should be behind the backdrop

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#723]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The footer is above the sidebar's backdrop.

## Expected behavior
The footer should be inside the sidebar content.

**Comment by christophercr** [comment]
Closed in #746
