### ISSUE TITLE
build: make sure we fully comply with the Angular Package Format (APF)

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#73]
cfr Angular package format (APF): https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview 

Things to do we've identified so far:
* [x] add missing properties in package.json for each package
* [x] add missing properties in tsconfig.json for each package
* [ ] sub-packages: add missing sub-packages support in the build.sh script
* [ ] sub-packages: add sub-package for e2e support in stark-core as example and make sure it works. Concrete example: https://github.com/angular/angular/tree/master/packages/core/testing and https://github.com/dherges/ng-packagr#secondary-entry-points
* [ ] add testing folder to each package (and review how it's handled in angular build)

**Comment by ncedric** [comment]
Done
