### ISSUE TITLE
ui: general - check cross-browser compatibility

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#732]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
I have checked briefly on internet explorer, doesn't look bad but some adjustments should be done.

## Expected behavior
Check the showcase on different browsers if the app is correctly displayed.

**Comment by christophercr** [comment]
Some issues found so far:

### On Internet Explorer:

**Message Pane demo page**
![issue-demo-message-pane](https://user-images.githubusercontent.com/5698318/48413557-5c7a9880-e748-11e8-8481-e1dbe5f13ca2.PNG)

And on mobile:
![issue-demo-message-pane-mobile](https://user-images.githubusercontent.com/5698318/48414362-c5fba680-e74a-11e8-803f-bdd8c6de66e2.PNG)



---
**Headings in most of the pages**
![issue-demo-pages-heading](https://user-images.githubusercontent.com/5698318/48413578-6e5c3b80-e748-11e8-9d76-4a0a6ed41e8b.PNG)

which is most likely related to this error in the console:
```
CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
Q4VhAPMA0GCSqGSIb3DQEBAQUABIGAHcF3ia6bbyLja+VF2k6RQPCf7zsfJ0pWrDr9qJRqfPecwX97k2BOG8QrV5WUyxbhmmcz0SspE8jsvrxZsQOkKZnsHYiZJId3D5vKFPvU1ElMdA7IPS5vIMkDzejlD9AhObNWGdX7rL2sqTi9sNUMo9ljrbCVtGhYw+LXKf+RpMcAAA==
```

---
**DatePicker**
The last days of the month bleed out of the picker:
![issue-demo-date-picker](https://user-images.githubusercontent.com/5698318/48413731-e88cc000-e748-11e8-9eb9-885b92e803e3.PNG)

---
**Table**

When showing the Global filter or any Column filter in the Table:
![issue-demo-table](https://user-images.githubusercontent.com/5698318/48413890-6781f880-e749-11e8-8361-f94675530a22.PNG)

This error is thrown:
```
"TypeError: Unable to get property 'opacity' of undefined or null reference
   at e.prototype.computeStyle (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:3732201)
   at Anonymous function (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:3723983)
   at forEach (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:215009)
   at Anonymous function (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:3723961)
   at forEach (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:215009)
   at Ze (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:3723928)
   at e.prototype._flushAnimations (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:3717275)
   at e.prototype.flush (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:3713800)
   at e.prototype.flush (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:3726324)
   at Anonymous function (http://localhost:8080/vendor.049f5eec4befc883d9cb.chunk.js:1:825282)"
```

---
**Menu on mobile**
The Stark icon is not centered:
![issue-menu-mobile](https://user-images.githubusercontent.com/5698318/48414232-6c937780-e74a-11e8-95d3-c825545def8d.PNG)

**Comment by cnomes** [comment]
dropdown schrinks in IE11
[
![screen recording 2019-01-02 at 14 26 36](https://user-images.githubusercontent.com/11627319/50593979-f33b1a00-0e9a-11e9-95ff-4860e226b626.gif)
](url)

**Comment by cnomes** [comment]
Pagination in IE11 shows error
![screen recording 2019-01-03 at 08 46 52](https://user-images.githubusercontent.com/11627319/50627595-78264200-0f34-11e9-8c11-9e54c1784517.gif)

**Comment by cnomes** [comment]
Fix for table filter proposed [here](https://github.com/angular/angular/issues/27887). Workaround added.

**Comment by cnomes** [comment]
The pretty print demo is broken.
![screenshot 2019-01-03 at 12 16 18](https://user-images.githubusercontent.com/11627319/50635184-73bc5200-0f51-11e9-9183-094ec017e674.png)
