### ISSUE TITLE
showcase: remove the login page

### ISSUE THREAD

**Issue by Mallikki** [NationalBankBelgium/stark#740]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
A login page is displayed when we go to https://stark.nbb.be

## Expected behavior

We need to remove that page for the next release

**Comment by SuperITMan** [comment]
Good idea. We could maybe create a page to show the 4 available pages :blush:
What do you think about this for later?

**Comment by christophercr** [comment]
@Mallikki Yes, for that we should first solve #727
