### ISSUE TITLE
ui: fonts - cannot use Roboto as font family, browser uses Serif as fallback

### ISSUE THREAD

**Issue by christophercr** [NationalBankBelgium/stark#768]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

The browser displays the content in `serif` When the font-family is set to an specific font, i.e. Roboto via the `$stark-typography-theme` map, the browser renders the content with `serif` instead.

## Expected behavior

The browser should display the content in the custom font-family specified in the `$stark-typography-theme` map.

## Minimal reproduction of the problem with instructions

In the Showcase or Starter

1.	Copy your new font(s) into the folder `projectFolder/src/assets/fonts/`
2.	Make sure that the angular.json file (this is the file used by Angular CLI and also Stark to customize the Webpack builds PROD and DEV) has an entry matching the assets files in order to copy those fonts as part of the webpack build:
 `projects -> yourApp ("showcase" or "starter") -> architect -> build -> options -> assets `

3.	Adapt the file `projectFolder/src/styles/_variables.scss` to import the fonts first and then create your custom `$stark-typography-theme` customizing the font-family:
```css
@import url("the path to your fonts");

$stark-typography-theme: (
  font-family: "Roboto, sans-serif"
);
```

## What is the motivation / use case for changing the behavior?

The app look and feel should be fully customizable by the developer, including the fonts

## Environment

<pre><code>
Angular version: 6.1.8
Stark version: 10.0.0-beta.0

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
</code></pre>

**Comment by cnomes** [comment]
The way to import a local font is to use `@font-face` eg:
```
@font-face {
  font-family: "Roboto";
  font-style: "Regular";
  src: url("/assets/fonts/Roboto-Regular.ttf") format("truetype")
}

$stark-typography-theme: (
  font-family: "'Roboto',  Sans-Serif",
);
```
if the font is added to the `assets/fonts` and angular.json is correctly configured (as specified above) the font should work.

If fonts should be loaded from external sources (CDN) eg:
```
@import url('https://fonts.googleapis.com/css?family=Roboto');

$stark-typography-theme: (
  font-family: "'Roboto',  Sans-Serif",
);
```
the [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) `font-src` should be adjusted to reflect the chosen CDN: 
`font-src 'self' https://fonts.gstatic.com;`
