### ISSUE TITLE
showcase: improve home page and news page

### ISSUE THREAD

**Issue by Mallikki** [NationalBankBelgium/stark#789]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Expected behavior
We need to improve the showcase and news pages. 
Take example on https://angular.io/ or https://ionicframework.com/.

**Comment by christophercr** [comment]
Solved in #1128
