### ISSUE TITLE
doc: update and publish developer guide

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#79]
Review and publish our developer guide: https://github.com/NationalBankBelgium/stark/issues?q=is%3Aissue+is%3Aopen+guide+label%3A%22comp%3A+developer-guide%22

* [ ] architecture
* [ ] services
* [ ] components
* [ ] API
* [ ] how to guides
* [ ] demos
* [ ] living style guide
* [ ] validation (#92)
* [ ] web design, css, html
  * [ ] CSS/PostCSS... (#242)
* [ ] accessibility (#217)
* [ ] PWA (#109)
* [ ] focus service (#224)
* [ ] testing
  * [ ] e2e (#237)
* [ ] security
  * [ ] protecting against HTML extraction (#226)
  * [ ] CSP
  * [ ] ...

**Comment by christophercr** [comment]
The Developer Guide is now included with the API docs generated by compodoc thanks to #1198 . It takes the MD files under `/docs` folder for the specific package: stark-core and stark-ui.

We still need to write more documentation in that Developer Guide, however that will be tackled in the different issues referenced in this one ;)
