### ISSUE TITLE
ui: generic search - implement component/module

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#794]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Expected behavior
Implement the generic search component as it is required by multiple existing projects

**Comment by christophercr** [comment]
@Mallikki these are some ideas for the search component 😉 

https://material.io/design/navigation/search.html#expandable-search
https://teradata.github.io/covalent/#/components/search

**Comment by SuperITMan** [comment]
I think we are mixing things here :stuck_out_tongue_winking_eye:
The issue is for the generic search component with abstract controller, service, etc. as we had in the old Stark 😊
I think we should create a new issue for the search route component.

**Comment by christophercr** [comment]
Oops, my bad 😢 So I removed my previous comment and will put it in a new issue
