### ISSUE TITLE
core: http - Error when performing a request with loggingFlushDisabled set to true

### ISSUE THREAD

**Issue by erwan-carlig** [NationalBankBelgium/stark#856]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When deserializing the `stark-app-config.json` (app.module.ts:99), by default the "loggingCorrelationIdHttpHeaderName" property is either set to the content of `stark-app-config.json` or to "correlation-id" (it can never be undefined).

If logging is disabled (`loggingFlushDisabled` set to true), the StarkLoggingServiceImpl will not generate a correlationId ([logging.service.ts:69](https://github.com/NationalBankBelgium/stark/blob/10.0.0-beta.1/packages/stark-core/src/modules/logging/services/logging.service.ts#L69)).

When using the stark http service, it will try to add the correlation headers ([http.service.ts:176](https://github.com/NationalBankBelgium/stark/blob/10.0.0-beta.1/packages/stark-core/src/modules/http/services/http.service.ts#L176)) and set the correlation id header to the value of correlationId coming from the StarkLoggingService (which is undefined since it was not generated).

When trying to perform the request it will cause any of the following errors: 
```
ERROR TypeError: Cannot read property 'keys' of undefined
    at StarkHttpServiceImpl.ac_main../node_modules/@nationalbankbelgium/stark-core/fesm5/stark-core.js.StarkHttpServiceImpl.getResponseHeaders 
```

```
"Cannot read property 'length' of undefined" in file headers.ts:74 (@angular/common/http/src/headers.ts)
```

## Expected behavior
No correlation header should be added if logging is disabled.

## Others:
Not a pressing issue, I can work around it.

## Environment

<pre><code>
Angular version: 6.1.10
Stark version: 10.0.0-beta.1

</code></pre>

**Comment by christophercr** [comment]
Thanks for the report! We'll fix it in the next release ;)

**Comment by erwan-carlig** [comment]
Hello,

Unfortunately the "loggingCorrelationIdHttpHeaderName" is added by the StarkHttpService's method "addCorrelationIdentifierHeader", which directly access the headers map and add the undefined header.
This bypass the StarkAbstractHttpBaseRequestBuilder method "setHeader" where you added an undefined check, hence the bug still occurs.

Thanks for the help :)
