### ISSUE TITLE
build: implement builders for using with NG CLI

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#883]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

We use npm scripts to run our application.

## Expected behavior

We should use the CLI build and add our customisations thanks to angular builders in stark-build.

## What is the motivation / use case for changing the behavior?

Angular team is improving the build system a lot (performance, bundle size, etc.) and we should take advantage of this instead of trying to follow them progressively.

**Comment by SuperITMan** [comment]
this is linked to #114

**Comment by dsebastien** [comment]
Great!
This will contribute to #146

**Comment by dsebastien** [comment]
Any chance of getting a better integration with Angular CLI in the coming releases?

**Comment by christophercr** [comment]
Indeed, we'll work on it in the coming weeks so we plan to include it in the first RC 😉

**Comment by christophercr** [comment]
We will use [@angular-builders](https://github.com/meltedspark/angular-builders) to customize the webpack config to be used with Angular CLI.

https://codeburst.io/customizing-angular-cli-6-build-an-alternative-to-ng-eject-a48304cd3b21
https://medium.com/dailyjs/angular-cli-6-under-the-hood-builders-demystified-f0690ebcf01
