### ISSUE TITLE
core: migrate NG1 providers

### ISSUE THREAD

**Issue by dsebastien** [NationalBankBelgium/stark#99]
With NG2+, the concept of providers is no longer the same and they don't exist anymore as they used to be in AngularJS.

We should convert the Providers we currently have in Stark  into the Angular2+ way:

* StoreProvider (perhaps this is obsolete as we move to NgRx v4)
* ToastNotificationProvider

**Comment by christophercr** [comment]
This issue can be closed now:

- The StoreProvider is now obsolete since we use now the official NGRX library for Angular2+.
- The ToastNotificationProvider has been migrated to the new Angular2+ way in this PR #707 (passing the config via the module's `forRoot()` method)
