### ISSUE TITLE
ui: App-menu - should be closed when entry is selected

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#995]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When we open the menu and we click on the entry to navigate to a new page, the menu stays on the page (small screens, tablet & mobile) until we click somewhere else.

## Expected behavior

When the entry in the menu is clicked, the menu should disappear immediately (small screens, tablet & mobile) instead of forcing the user to click outside the menu to make it disappear.

## What is the motivation / use case for changing the behavior?

Improve the user experience.

**Comment by cnomes** [comment]
Related to #732
